use std::net::TcpListener;
use std::process::Command;
use tempfile::TempDir;

use git_nfs::git::gcs_storage::{format_info_packs, format_info_refs};

#[test]
fn test_git_clone_with_generated_server_info() -> anyhow::Result<()> {
    // 1. Create a bare git repository
    let temp = TempDir::new()?;
    let repo_dir = temp.path().join("repo.git");
    let work_dir = temp.path().join("work");
    let clone_dir = temp.path().join("cloned");

    let status = Command::new("git")
        .args(["init", "--bare", repo_dir.to_str().unwrap()])
        .status()?;
    assert!(status.success());

    // 2. Clone locally to make a commit and a tag
    let status = Command::new("git")
        .args(["clone", repo_dir.to_str().unwrap(), work_dir.to_str().unwrap()])
        .status()?;
    assert!(status.success());

    Command::new("git")
        .args(["-C", work_dir.to_str().unwrap(), "config", "user.name", "Test User"])
        .status()?;
    Command::new("git")
        .args(["-C", work_dir.to_str().unwrap(), "config", "user.email", "test@example.com"])
        .status()?;

    let test_file = work_dir.join("hello.txt");
    std::fs::write(&test_file, b"Hello world from git-nfs!\n")?;

    Command::new("git")
        .args(["-C", work_dir.to_str().unwrap(), "add", "."])
        .status()?;
    Command::new("git")
        .args(["-C", work_dir.to_str().unwrap(), "commit", "-m", "First commit"])
        .status()?;
    Command::new("git")
        .args(["-C", work_dir.to_str().unwrap(), "tag", "-a", "v1.0", "-m", "Version 1.0"])
        .status()?;
    Command::new("git")
        .args(["-C", work_dir.to_str().unwrap(), "push", "origin", "HEAD:refs/heads/master", "--tags"])
        .status()?;

    // 3. Pack objects in bare repo so objects/pack/ has a .pack and .idx
    Command::new("git")
        .args(["-C", repo_dir.to_str().unwrap(), "repack", "-a", "-d"])
        .status()?;

    // 4. Ensure HEAD is a symbolic ref to refs/heads/master
    std::fs::write(repo_dir.join("HEAD"), b"ref: refs/heads/master\n")?;

    // 5. Generate info/refs using our format_info_refs implementation
    let master_sha = std::fs::read_to_string(repo_dir.join("refs/heads/master"))?
        .trim()
        .to_string();
    let tag_sha = std::fs::read_to_string(repo_dir.join("refs/tags/v1.0"))?
        .trim()
        .to_string();

    let entries = vec![
        ("refs/heads/master".to_string(), master_sha.clone(), None),
        ("refs/tags/v1.0".to_string(), tag_sha.clone(), Some(master_sha.clone())),
    ];

    let info_refs_content = format_info_refs(&entries);
    let info_dir = repo_dir.join("info");
    std::fs::create_dir_all(&info_dir)?;
    std::fs::write(info_dir.join("refs"), info_refs_content.as_bytes())?;

    // 6. Generate objects/info/packs using our format_info_packs implementation
    let pack_dir = repo_dir.join("objects/pack");
    let mut pack_names = Vec::new();
    for entry in std::fs::read_dir(&pack_dir)? {
        let entry = entry?;
        let filename = entry.file_name().to_string_lossy().to_string();
        if filename.ends_with(".pack") {
            pack_names.push(filename);
        }
    }
    assert!(!pack_names.is_empty(), "Packfile should have been generated by git repack");

    let info_packs_content = format_info_packs(&pack_names);
    let objects_info_dir = repo_dir.join("objects/info");
    std::fs::create_dir_all(&objects_info_dir)?;
    std::fs::write(objects_info_dir.join("packs"), info_packs_content.as_bytes())?;

    // 7. Start a static HTTP server serving temp.path()
    // Find an available port
    let listener = TcpListener::bind("127.0.0.1:0")?;
    let port = listener.local_addr()?.port();
    drop(listener);

    let root_path = temp.path().to_path_buf();
    let mut server = Command::new("python3")
        .args([
            "-m",
            "http.server",
            &port.to_string(),
            "--bind",
            "127.0.0.1",
            "--directory",
            root_path.to_str().unwrap(),
        ])
        .spawn()?;

    // Wait for server to bind
    std::thread::sleep(std::time::Duration::from_millis(500));

    // 8. Run git clone against the HTTP server
    let clone_url = format!("http://127.0.0.1:{port}/repo.git");
    let clone_output = Command::new("git")
        .args(["clone", &clone_url, clone_dir.to_str().unwrap()])
        .output();

    // Kill server
    let _ = server.kill();

    let output = clone_output?;
    let stderr = String::from_utf8_lossy(&output.stderr);
    let stdout = String::from_utf8_lossy(&output.stdout);
    println!("git clone stdout:\n{stdout}");
    println!("git clone stderr:\n{stderr}");

    assert!(
        output.status.success(),
        "git clone failed with status {:?}:\n{}",
        output.status,
        stderr
    );

    // Verify checked-out file
    let cloned_file = clone_dir.join("hello.txt");
    assert!(cloned_file.is_file(), "Cloned file hello.txt must exist");
    assert_eq!(
        std::fs::read_to_string(&cloned_file)?,
        "Hello world from git-nfs!\n"
    );

    // Verify no warnings about nonexistent HEAD ref
    assert!(
        !stderr.contains("remote HEAD refers to nonexistent ref"),
        "Should cleanly check out default branch without HEAD warning"
    );

    Ok(())
}
